services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    ports:
      - 8091:8091
    environment:
      - IS_DOCKER=1
      - RUN_SERVICES=API
      - PORT_NUMBER=8091
  jonbot:
    build:
      context: ..
      dockerfile: docker/Dockerfile.discord
    depends_on:
      - api
    environment:
      - IS_DOCKER=1
      - RUN_SERVICES=DISCORD
      - PORT_NUMBER=8091


version: '3.7'